---
title: 'STAA 577: Laboratory Seven (II) </br> `tidyverse` version'
author: 'Adapted by Tavener & Field </br> From: James, Witten, Hastie and Tibshirani'
date: "`r format(Sys.Date(), '%e %B %Y')`"
output:
  html_notebook: 
    code_folding: show
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
ratio: '9:16'
tables: yes
fontsize: 12pt
---



```{r setup, include = FALSE}
options(warnPartialMatchArgs = FALSE)  # don't want these warnings
library(magrittr)     # pipes
library(tibble)       # tibbles
library(dplyr)        # data wrangling
library(boot)         # for `cv.glm`
library(purrr)        # iteration
library(ggplot2)      # tidy plotting
library(ISLR)         # Wage data set
library(splines)      # fitting splines
```

```{r data}
#fix(Wage)
dim(Wage)
agelims<-range(age)
age.grid<-seq(from=agelims[1],to=agelims[2])
```

# Splines

```{r splines}
# Fit b-spline (by default a cubic spline) and plot spline + 2*standard error bounds
fit<-lm(wage~bs(age,knots=c(25,40,60)),data=Wage)
pred<-predict(fit,newdata=list(age=age.grid),se=T)
plot(age,wage,col="gray")
lines(age.grid,pred$fit,lwd=2)
lines(age.grid,pred$fit+2*pred$se,lty="dashed")
lines(age.grid,pred$fit-2*pred$se,lty="dashed")

# df=(number of degrees of freedom) locates knots based on uniform percentiles of the data
dim(bs(age,knots=c(25,40,60)))
dim(bs(age,df=6))
attr(bs(age,df=6),"knots")

# Fit a natural spline with four dof
fit2<-lm(wage~ns(age,df=4),data=Wage)
pred2<-predict(fit2,newdata=list(age=age.grid),se=T)
lines(age.grid, pred2$fit,col="red",lwd=2)
```

------------------------


# Smoothing Splines
  
```{r smoothing_splines}
# Fit a smoothing spline
plot(age,wage,xlim=agelims,cex=.5,col="darkgrey")
title("Smoothing Spline")
fit<-smooth.spline(age,wage,df=16)

# Select level of smoothness by cross validation

fit2<-smooth.spline(age,wage,cv=TRUE)
fit2$df
lines(fit,col="red",lwd=2)
lines(fit2,col="blue",lwd=2)
legend("topright", legend=c("16 DF","6.8 DF"),col=c("red","blue"),lty=1,lwd=2,cex=.8)
```

--------------------------




# General Additive Models

```{r GAMs}
# Sum of two natural splines and a linear function
gam1<-lm(wage~ns(year,4)+ns(age,5)+education,data=Wage)
library(gam)

# Sum of two splines and a linear function
gam.m3<-gam(wage~s(year,4)+s(age,5)+education,data=Wage)
par(mfrow=c(1,3))
plot(gam.m3, se=TRUE,col="blue")
plot(gam1, se=TRUE, col="red")
```

```{r GAMs, eval=TRUE}
# Construct a two new models and compare using ANOVA
gam.m1<-gam(wage~s(age,5)+education,data=Wage)
gam.m2<-gam(wage~year+s(age,5)+education,data=Wage)
anova(gam.m1,gam.m2,gam.m3,test="F")
summary(gam.m3)
preds<-predict(gam.m2,newdata=Wage)
preds
```

